- hosts: master
  gather_facts: no
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:    
    - name: Add "{{repo_name}}" "{{repo_url}}"
      shell: helm repo add "{{repo_name}}" "{{repo_url}}"
    
    - set_fact:
        random_name: "/tmp/{{helm_name}}_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}.json"
      when: values is defined
    
    - local_action: copy content="{{ values }}" dest={{random_name}}
      when: values is defined
    
    - copy:
        src: "{{random_name}}"
        dest: "{{random_name}}"
      when: values is defined

    - shell: helm uninstall "{{helm_name}}"
      ignore_errors: yes

    - shell: helm upgrade --install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
      register: helm_install_output
      until: helm_install_output.rc == 0
      retries: 15
      delay: 2
      when: values is defined
      
      
    - shell: helm upgrade --install "{{helm_name}}" "{{chart_name}}" 
      register: helm_install_output
      until: helm_install_output.rc == 0
      retries: 15
      delay: 2
      when: values is not defined
      
            
    - shell: kubectl get pod/"{{helm_name}}" -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('status.phase==`"{{status}}"`')
      retries: 200
      delay: 6
      when: status is defined
      
      
    - include: get_argo_token.yaml
      when: chart_name == "argo/argo-workflows"
      register: argo_token


    - debug: 
        var: argo_token.stdout
      when: chart_name == "argo/argo-workflows"
      
      
    - set_stats:
        data:
          argo_token: 
            token_type: argo_token
            token: "{{argo_token.stdout}}"
      when: chart_name == "argo/argo-workflows"
      
  
      
