- hosts: master
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:    
  
    - shell: helm repo add "{{repo_name}}" "{{repo_url}}"
    
    - set_fact:
        random_name: "helm_values_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
    
    - local_action: copy content="{{ values }}" dest=/tmp/"{{random_name}}"_"{{helm_name}}".yaml
    
    - copy:
        src: /tmp/helm_values.yaml
        dest: /tmp/helm_values.yaml
     
    - shell: helm uninstall "{{helm_name}}"
      ignore_errors: yes
    
    
    - shell: helm install "{{helm_name}}" "{{chart_name}}"  -f /tmp/"{{random_name}}"_"{{helm_name}}".yaml
      register: helm_install_output
            
    - shell: kubectl get pod/"{{helm_name}}" -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('status.phase==`"{{status}}"`')
      retries: 150
      delay: 10
      when: status is defined
  
  


      
