- hosts: master
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:    
  
    - shell: helm repo add "{{repo_name}}" "{{repo_url}}"
    
    - local_action: copy content="{{ values }}" dest=/tmp/helm_values.yaml
    
    - copy:
        src: /tmp/helm_values.yaml
        dest: /tmp/helm_values.yaml
     
    - shell: helm uninstall "{{helm_name}}"
      ignore_errors: yes
    
    
    - shell: helm install "{{helm_name}}" "{{chart_name}}"  -f /tmp/helm_values.yaml
      register: helm_install_output
      
    - pause:
        seconds: 2
    
      
    - shell: kubectl get pod/"{{helm_name}}" -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('status.phase')|unique == ["{{status}}"]
      when: status is defined
  
  


      
