- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3

  tasks:
  
    - package:
        name:
          - jq
        state: present
      become: yes 

    - pip:
        name: pip
        state: latest

    - apt: 
        name:
          - software-properties-common
        update_cache: yes
      become: yes 
        
    - apt_repository: 
        repo: ppa:ansible/ansible
        state: present
        update_cache: yes
      become: yes 
      
    - apt: 
        name:
          - ansible
        update_cache: yes
      become: yes 
           
    - shell: ansible --version
      register: ansible_v_output

    - debug:
        var: ansible_v_output

    - shell: ansible-galaxy collection install community.general
      register: ansible_galaxy_output

    - debug:
        var: ansible_galaxy_output
        
           
#   - snap:
#       name:
#         - helm
#     register: snap_out
      
#   - debug:
#       var: snap_out
