- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
      - apt:
          name: jq
          state: present
    
#     - package:
#         name:
#         - jq
#         state: present
# #      become: yes
       
    
    - snap:
        name:
          - helm
        classic: yes
      become: yes
      
     
      
