- hosts: master
#   vars:
#       ansible_python_interpreter: /usr/bin/python3

  tasks:
  

  - apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
    
    
  - apt:
      pkg:
      - jq
      - ansible
      update_cache: yes
    become: yes    
    

    - pip:
        name: pip
        state: latest

#     - pip:
#         name:
#           - ansible[azure]
#         state: forcereinstall

    - shell: ansible --version
      register: ansible_v_output
      
      
    - debug:
        var: ansible_v_output
      
      
    - shell: ansible-galaxy collection install community.general
      register: ansible_galaxy_output
      
    - debug:
        var: ansible_galaxy_output
        
           
    - snap:
        name:
          - helm
      register: snap_out
      
    - debug:
        var: snap_out
