- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3
   become: yes
  collections:
    - community.general
  tasks:
    - package:
        name:
        - jq
        - python3-pip
        state: present
        
        
#     - apt:
#         name: 
#           - jq
#           - python3-pip
#         update_cache: yes
#       become: yes


    - pip:
        name: pip
        state: latest

    - snap:
        name:
          - helm
        classic: yes
      register: status
      until: not status.failed
      retries: 10

    - debug:
        var: status
