- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3

  tasks:
   - package:
      name:
        - jq
      state: present
     become: yes 
    

   - pip:
      name: pip
      state: latest

   - pip:
      name: ansible
      state: absent
      
    - shell: apt purge ansible*
      become: yes
      
   - pip:
      name: ansible
      version: '2.9'
      state: forcereinstall
        
   - shell: ansible --version
     register: ansible_v_output
    
   - debug:
      var: ansible_v_output
         
   - shell: ansible-galaxy collection install community.general
     register: ansible_galaxy_output
      
   - debug:
      var: ansible_galaxy_output
        
           
#   - snap:
#       name:
#         - helm
#     register: snap_out
      
#   - debug:
#       var: snap_out
