- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general

  tasks:
  
    - package:
        name:
        - jq
        - gcc
        - python3-devel
        state: present
#      become: yes
       
    
    - snap:
        name:
          - helm
        classic: yes
      become: yes
      
     
      
