- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general
  tasks:
    - package:
        name:
        - jq
        state: present
#      become: yes

    - pip:
        name: pip
        state: latest
