- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general
  tasks:
    - apt:
        name: 
          - jq
          - python3-pip
        update_cache: yes
      become: yes


    - pip:
        name: pip
        state: latest

    - snap:
        name:
          - helm
        classic: yes
      become: yes
      register: status
#       until: status.json.status == "READY"


    - debug:
        var: status
