- hosts: master
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
  
    - helm:
        host: localhost
        chart:
          name: "{{chart_name}}"
          source:
            type: "{{repo_type}}"
            location: "{{repo_url}}"
        state: present
        name: "{{name}}"
        namespace: "{{namespace}}"
      
