- hosts: master
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:    
  
    - shell: helm repo add "{{repo_name}}" "{{repo_url}}"
    
    - local_action: copy content="{{ values }}" dest=/tmp/helm_values.yaml
    
   - copy:
      src: /tmp/helm_values.yaml
      dest: /tmp/helm_values.yaml
     
        
    - shell: helm install "{{name}}" "{{chart_name}}"  -f /tmp/helm_values.yaml
    
#     - community.kubernetes.helm:
#         host: localhost
#         chart:
#           name: "{{chart_name}}"
#           source:
#             type: "{{repo_type}}"
#             location: "{{repo_url}}"
#         state: present
#         name: "{{name}}"
#         namespace: "{{namespace}}"
      
