- hosts: master
  gather_facts: no
  become: yes
  vars:
   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general
  tasks:
    - package:
        name:
        - jq
        - python3-pip
        - nfs-common
        state: present
        
    - pip:
        name: pip
        state: latest

    - snap:
        name:
          - helm
        classic: yes
      register: status
      until: not status.failed
      retries: 20

    - debug:
        var: status
