- hosts: master
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:
      - helm:
          name: "{{helm_name}}"
          chart_ref: "{{ref}}"
          repo_url: "{{location}}"
      
