- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3

  tasks:
  
    - package:
        name:
          - jq
          - git
        state: present
      become: yes 

    - pip:
        name: pip
        state: latest
        

    - pip:
        name: 
          - pyhelm
        state: present
        
        

    - apt: 
        name:
          - software-properties-common
        update_cache: yes
      become: yes 
        
    - apt_repository: 
        repo: ppa:ansible/ansible
        state: present
        update_cache: yes
      become: yes 
      
    - apt: 
        name:
          - ansible
        update_cache: yes
      become: yes 


    - shell: ansible-galaxy collection install -p $HOME/.ansible/roles community.general
      register: ansible_galaxy_output
      
