- hosts: master
#   vars:
#       ansible_python_interpreter: /usr/bin/python3

  tasks:
    - package:
        name:
        - jq
        state: present
#      become: yes

    - pip:
        name: pip
        state: latest

#     - pip:
#         name:
#           - ansible[azure]
#         state: forcereinstall


    - shell: ansible-galaxy collection install community.general
