- hosts: master
  vars:
   ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.general
  tasks:
    - apt:
      name: jq
      update_cache: yes

    - pip:
        name: pip
        state: latest
