- hosts: master
  gather_facts: no
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:    
    - name: Remove "{{repo_name}}"
      shell: helm repo remove "{{repo_name}}"
      ignore_errors: yes
      

    - name: Add "{{repo_name}}" "{{repo_url}}"
      shell: helm repo add "{{repo_name}}" "{{repo_url}}"
      retries: 5
      delay: 1    
      
    - name: update repos
      shell: helm repo update
      retries: 2
      delay: 1    

    - set_fact:
        random_name: "/tmp/{{helm_name}}_{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}.json"
      when: values is defined
    
    
    - local_action: copy content="{{ values }}" dest={{random_name}}
      when: values is defined
    
    - name: Copy "{{ values }}" to "{{random_name}}"
      copy:
        src: "{{random_name}}"
        dest: "{{random_name}}"
      when: values is defined

    - name: helm uninstall "{{helm_name}}"
      shell: helm uninstall "{{helm_name}}"
      ignore_errors: yes

    - name: helm install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
#       shell: helm upgrade --install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
      shell: helm install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
      register: helm_install_output_try1
      when: values is defined
            
    - name: Error with installation. Running helm uninstall "{{helm_name}}"
      shell: helm uninstall "{{helm_name}}"
      ignore_errors: yes
      when: helm_install_output_try1.rc != 0
      
    - name: Error with installation. Running kubectl delete mutatingwebhookconfiguration/monitoring-kube-prometheus-admission
      shell: kubectl delete mutatingwebhookconfiguration/monitoring-kube-prometheus-admission
      ignore_errors: yes
      when: helm_install_output_try1.rc != 0
      
    - name: helm install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
#       shell: helm upgrade --install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
      shell: helm install "{{helm_name}}" "{{chart_name}}"  -f {{random_name}}
      when: helm_install_output_try1.rc != 0
      
      
    - name: helm install "{{helm_name}}" "{{chart_name}}" 
#       shell: helm upgrade --install "{{helm_name}}" "{{chart_name}}" 
      shell: helm install "{{helm_name}}" "{{chart_name}}" 
      register: helm_install_output_try1
      when: values is not defined     
     
      
            
    - name: kubectl get pod/"{{helm_name}}" -o json
      shell: kubectl get pod/"{{helm_name}}" -o json
      register: kubectl_get_pods
      until: kubectl_get_pods.stdout|from_json|json_query('status.phase==`"{{status}}"`')
      retries: 200
      delay: 6
      when: status is defined
      
      
    - include: get_argo_token.yaml
      when: chart_name == "argo/argo-workflows"
      register: argo_token


    - debug: 
        var: argo_token.stdout
      when: chart_name == "argo/argo-workflows"
      
      
    - set_stats:
        data:
          argo_token: 
            token_type: argo_token
            token: "{{argo_token.stdout}}"
      when: chart_name == "argo/argo-workflows"
      
  
      
